// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrafficCounter.Api.Data;

#nullable disable

namespace TrafficCounter.Api.Migrations
{
    [DbContext(typeof(TrafficCounterDbContext))]
    partial class TrafficCounterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("TrafficCounter.Api.Models.CameraConfig", b =>
                {
                    b.Property<string>("CameraId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CountDirection")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("CountLineX1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountLineX2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountLineY1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountLineY2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoiH")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoiW")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoiX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoiY")
                        .HasColumnType("INTEGER");

                    b.HasKey("CameraId");

                    b.ToTable("CameraConfigs");
                });

            modelBuilder.Entity("TrafficCounter.Api.Models.CountEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CameraId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CrossedAt")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoundId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrackId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoundId", "TrackId");

                    b.ToTable("CountEvents");
                });

            modelBuilder.Entity("TrafficCounter.Api.Models.Round", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FinalCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("TrafficCounter.Api.Models.RoundRange", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Max")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Min")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Odds")
                        .HasColumnType("REAL");

                    b.Property<string>("RoundId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoundId");

                    b.ToTable("RoundRanges");
                });

            modelBuilder.Entity("TrafficCounter.Api.Models.RoundRange", b =>
                {
                    b.HasOne("TrafficCounter.Api.Models.Round", null)
                        .WithMany("Ranges")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrafficCounter.Api.Models.Round", b =>
                {
                    b.Navigation("Ranges");
                });
#pragma warning restore 612, 618
        }
    }
}
