// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrafficCounter.Api.Data;

#nullable disable

namespace TrafficCounter.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260413221103_AddCameraRoundStateSourceSnapshot")]
    partial class AddCameraRoundStateSourceSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("TrafficCounter.Api.Domain.Entities.Bet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AcceptedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CameraId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("GameSessionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketLabel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Max")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Min")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Odds")
                        .HasColumnType("numeric(10,4)");

                    b.Property<string>("OperatorRef")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerRef")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PotentialPayout")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ProviderBetId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RollbackOfTransactionId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoundMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SettledAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StakeAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TargetValue")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Threshold")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VoidedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("ProviderBetId")
                        .IsUnique();

                    b.HasIndex("RoundId");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.HasIndex("RoundId", "Status");

                    b.ToTable("Bets");
                });

            modelBuilder.Entity("TrafficCounter.Api.Domain.Entities.CameraRoundState", b =>
                {
                    b.Property<string>("CameraId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveStreamProfileId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastProfileChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSourceChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSourceFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSourceUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("RoundsSinceProfileSwitch")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("CameraId");

                    b.HasIndex("ActiveStreamProfileId");

                    b.ToTable("CameraRoundStates");
                });

            modelBuilder.Entity("TrafficCounter.Api.Domain.Entities.CameraSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CameraSources");
                });

            modelBuilder.Entity("TrafficCounter.Api.Domain.Entities.RecordingSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SegmentType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("RecordingSegments");
                });

            modelBuilder.Entity("TrafficCounter.Api.Domain.Entities.Round", b =>
                {
                    b.Property<Guid>("RoundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BetCloseAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CameraId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FinalCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoundMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SettledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("VoidReason")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VoidedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("RoundId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("CameraId", "Status");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("TrafficCounter.Api.Domain.Entities.RoundEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CountValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoundStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoundId", "EventType");

                    b.HasIndex("RoundId", "TimestampUtc");

                    b.ToTable("RoundEvents");
                });

            modelBuilder.Entity("TrafficCounter.Api.Domain.Entities.RoundMarket", b =>
                {
                    b.Property<Guid>("MarketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsWinner")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Max")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Min")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Odds")
                        .HasColumnType("numeric(10,4)");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TargetValue")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Threshold")
                        .HasColumnType("INTEGER");

                    b.HasKey("MarketId");

                    b.HasIndex("RoundId");

                    b.ToTable("RoundMarkets");
                });

            modelBuilder.Entity("TrafficCounter.Api.Domain.Entities.StreamHealthLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("FpsIn")
                        .HasColumnType("REAL");

                    b.Property<double>("FpsOut")
                        .HasColumnType("REAL");

                    b.Property<double>("GpuUsagePercent")
                        .HasColumnType("REAL");

                    b.Property<double>("LatencyMs")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReconnectCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("StreamHealthLogs");
                });

            modelBuilder.Entity("TrafficCounter.Api.Domain.Entities.StreamSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CameraSourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CountDirection")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("CountLineX1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountLineX2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountLineY1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountLineY2")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessedStreamPath")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawStreamPath")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StoppedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CameraSourceId");

                    b.HasIndex("Status");

                    b.ToTable("StreamSessions");
                });

            modelBuilder.Entity("TrafficCounter.Api.Domain.Entities.VehicleCrossingEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CameraId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<int?>("CountAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CountBefore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("FrameNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LineId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectClass")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousEventHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RoundId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("StreamProfileId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("TrackId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventHash");

                    b.HasIndex("RoundId");

                    b.HasIndex("RoundId", "TimestampUtc");

                    b.HasIndex("SessionId", "TimestampUtc");

                    b.ToTable("VehicleCrossingEvents");
                });

            modelBuilder.Entity("TrafficCounter.Api.Domain.Entities.Bet", b =>
                {
                    b.HasOne("TrafficCounter.Api.Domain.Entities.Round", "Round")
                        .WithMany("Bets")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("TrafficCounter.Api.Domain.Entities.RecordingSegment", b =>
                {
                    b.HasOne("TrafficCounter.Api.Domain.Entities.StreamSession", "Session")
                        .WithMany("RecordingSegments")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("TrafficCounter.Api.Domain.Entities.RoundEvent", b =>
                {
                    b.HasOne("TrafficCounter.Api.Domain.Entities.Round", "Round")
                        .WithMany("Events")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("TrafficCounter.Api.Domain.Entities.RoundMarket", b =>
                {
                    b.HasOne("TrafficCounter.Api.Domain.Entities.Round", "Round")
                        .WithMany("Markets")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("TrafficCounter.Api.Domain.Entities.StreamHealthLog", b =>
                {
                    b.HasOne("TrafficCounter.Api.Domain.Entities.StreamSession", "Session")
                        .WithMany("HealthLogs")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("TrafficCounter.Api.Domain.Entities.StreamSession", b =>
                {
                    b.HasOne("TrafficCounter.Api.Domain.Entities.CameraSource", "CameraSource")
                        .WithMany("Sessions")
                        .HasForeignKey("CameraSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CameraSource");
                });

            modelBuilder.Entity("TrafficCounter.Api.Domain.Entities.VehicleCrossingEvent", b =>
                {
                    b.HasOne("TrafficCounter.Api.Domain.Entities.StreamSession", "Session")
                        .WithMany("CrossingEvents")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Session");
                });

            modelBuilder.Entity("TrafficCounter.Api.Domain.Entities.CameraSource", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("TrafficCounter.Api.Domain.Entities.Round", b =>
                {
                    b.Navigation("Bets");

                    b.Navigation("Events");

                    b.Navigation("Markets");
                });

            modelBuilder.Entity("TrafficCounter.Api.Domain.Entities.StreamSession", b =>
                {
                    b.Navigation("CrossingEvents");

                    b.Navigation("HealthLogs");

                    b.Navigation("RecordingSegments");
                });
#pragma warning restore 612, 618
        }
    }
}
